name: Deploy - Async Messaging

on:
  push:
  workflow_dispatch:

# Required with 'Federal Credentials' to authenticate GitHub Actions with Azure Active Directory.
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@main      
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: 'Run az commands'
        run: az account get-access-token --scope=https://backend-app.i8cnl.onmicrosoft.com/.default --query accessToken --output tsv


      - uses: matt-ball/newman-action@master
        with:
          collection: ./tests/TestCollection.postman_collection.json
          envVar: '[{ "key": "access-token", "value": "http://localhost:3000" }]'